### ISSUE TITLE
Documentation for building CPP Branch

### ISSUE THREAD

**Issue by PhantomGamers** [Fabbi/autoshift#13]
I'm not very familiar with QT programs and I've been having trouble figuring out how to get this to build.

I'm trying to build for Windows but think I may be missing things, at minimum "extern_libs/QtWaitingSpinner" is missing.

Knowing what prerequisites are required here would be helpful.

Thanks for your work, this utility is quite handy!

**Comment by Fabbi** [comment]
I set this up on my Macbook and cross compiled the windows version, so the building process was quite hacky.. I am in the process of rewriting it, so it can be built more easily.
