### ISSUE TITLE
Any plans to switch or add Orcicorn as a source?

### ISSUE THREAD

**Issue by r3dshell** [Fabbi/autoshift#14]
The website is updated much more frequently for Borderlands 3 and has a RSS feed instead of a table.

https://shift.orcicorn.com/

**Comment by Fabbi** [comment]
thanks for that link. The site looks promising, I will look into this.

**Comment by Fabbi** [comment]
so I looked into this and while it seems promising it has one major flaw:
the RSS only shows the last 10 codes.

**Comment by Torsdan** [comment]
Can both be parsed and ignore duplicates?

**Comment by Fabbi** [comment]
sure, but what's the point? Is orcz so slow?

**Comment by Torsdan** [comment]
Orcz does appear to be ~4-6hrs late compared to Orcicorn.

**Comment by Torsdan** [comment]
Will this be available for python too?

**Comment by Fabbi** [comment]
soon™ 

you are right, sorry .

**Comment by Orcicorn** [comment]
> so I looked into this and while it seems promising it has one major flaw:
> the RSS only shows the last 10 codes.

Heya!   I also have a JSON feed that is generated every time the site is updated.  The codes are all of them that are valid at the time of the update.  There is no arbitrary limit on how many codes are returned like the RSS Feeds. The JSON feeds are available for all the same feeds as the XML one, just change the url extensions to .JSON

For example:

Recent SHiFT Codes (Arbitrarily 10)
https://shift.orcicorn.com/shift-code/index.xml

Becomes All Active SHiFT Codes
https://shift.orcicorn.com/shift-code/index.json

You can also just filter by game if you'd prefer
https://shift.orcicorn.com/tags/borderlands3/index.json

Hit me up on twitter/email/whatever if there's anything else I can help with.

**Comment by Fabbi** [comment]
I already did ;) Thanks for your comment and your awesome work!

**Comment by Torsdan** [comment]
Any further progress on this or other issues?
