### ISSUE TITLE
Dockerfile or arguments for credentials

### ISSUE THREAD

**Issue by Torsdan** [Fabbi/autoshift#15]
I'd like to have this running in a docker, is there currently a way to pass the username and password with the ./auto.py?
If not, would you be able to implement that or if you have knowledge with docker, create a dockerfile?

**Comment by Fabbi** [comment]
working on it

**Comment by Fabbi** [comment]
does it have to be the python version? I would like to replace this version with the c++ one

**Comment by Torsdan** [comment]
If the c++ works in docker, I don't mind. But I know python does work in docker and since it'll be running mostly headless, python would be a better choice.

**Comment by Fabbi** [comment]
done. should be working now.

**Comment by Torsdan** [comment]
Thank you for this.
> "--p" gives error "ambiguous option: --p could match --pass, --platforms" but --pass works.
> Is it possible to pass multiple args to --platform?
> Same for --games. If this one is to much effort that's fine, I can just start another docker for the other games.

**Comment by Torsdan** [comment]
@Confusingboat I have tried your dockerfile but it gives the following:
>Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"-e\": executable file not found in $PATH": unknown.

Using: docker run confusingboat/autoshift -e SHIFT_USER=** -e SHIFT_PASS=**

**Comment by Confusingboat** [comment]
@Torsdan looks like I goofed the example in the readme. The image `confusingboat/autoshift:latest` should come after all the `-e` and `-v` options. I'm running two instances of this on my k8s cluster so I can assure you the image itself works.

**Comment by Torsdan** [comment]
ah yes, there it goes. Thank you both for getting this going.

**Comment by Fabbi** [comment]
`--platforms` and `--games` both support multiple arguments. 
And you have to type at least `--pa` and `--pl` to distinguish between `pass` and `platforms`.

**Comment by Torsdan** [comment]
@Confusingboat Would @Fabbi have to register the dockerfile on hub.docker.com for it to be visible?

**Comment by Confusingboat** [comment]
@Torsdan I think you may be misunderstanding how dockerfiles work; they are just instructions for building a docker image. Docker Hub just hosts Docker images, and isn't inherently linked to GitHub at all. The images hosted there aren't even necessarily built by Docker's hosted build service.

In order be able to pull a `fabbi/autoshift` Docker image, @Fabbi would have to create a public repo on Docker Hub called `autoshift` that builds from this repository.

More infos here:
https://nickjanetakis.com/blog/differences-between-a-dockerfile-docker-image-and-docker-container

**Comment by Torsdan** [comment]
That is what I meant, since we wouldn't be able to install easily from within docker without that repo.
