### ISSUE TITLE
BL3 not redeeming for Epic

### ISSUE THREAD

**Issue by Torsdan** [Fabbi/autoshift#16]
It appears to be redeeming for Steam but not for Epic. Is there a way to either make sure it will do both (all even) or specify one?

**Comment by Fabbi** [comment]
yeah, I am sorry.. they changed the way those keys work. I actually fixed this already but didn't have time to upload a new release yet.. I'm trying to do so this weekend!

**Comment by Fabbi** [comment]
I uploaded a fixed version. Sorry that this took so long..

**Comment by Fabbi** [comment]
Oh, is this for the Python version?

**Comment by Torsdan** [comment]
Sorry, yes, this is was for the python version.

**Comment by Fabbi** [comment]
Yeah, that's on my todo list.
