### ISSUE TITLE
Qt5 and login error in Windows

### ISSUE THREAD

**Issue by DavidSpek** [Fabbi/autoshift#19]
After downloading the windows exe of the latest release, it could not load the Qt modules in the folder. After replacing these dll's with the ones I got from my Qt5 installation, the program did open. I then tried logging in, however, I got the error "login failed". I also built my own version from source which gave the same error. I could not find any logs to try and debug what is causing this. I did try making a firewall exception but this did not solve the problem. 
I am now going to try on MacOS to see if it does work there.

P.S. The latest build does not provide a prebuilt version for MacOS.

**Comment by DavidSpek** [comment]
I just built the C++ version on MacOS and I am able to login with this version.

**Comment by Fabbi** [comment]
Oh, that's strange.. What version of Windows do you have? 32/64?

I pushed some changes. If you compile it and run it with `-v` it will generate a `debug.log` which will hopefully help us find out what's causing the login issue.

For the prebuilt MacOS version I am trying to figure out how to properly package it into an *.app.

**Comment by DavidSpek** [comment]
I am running Windows 10 64 Bit, I'm using "C:/Qt/5.12.5/msvc2017_64/lib/cmake" in the FindQt5Extern.cmake. 

With the newest changes I am getting 2 build errors. 

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2679	binary '<<': no operator found which takes a right-hand operand of type 'const T' (or there is no acceptable conversion)
        with
        [
            T=QUrl
        ]	autoshift	C:\Users\David van der Spek\Downloads\autoshift-cpp\include\misc\logger.hpp	462	
Error	C2679	binary '<<': no operator found which takes a right-hand operand of type 'const T' (or there is no acceptable conversion)
        with
        [
            T=QUrl
        ]	autoshift	C:\Users\David van der Spek\Downloads\autoshift-cpp\include\misc\logger.hpp	445	
`

**Comment by DavidSpek** [comment]
So I just saw that a few hours after my post a new commit was submitted. With the now most current version I am able to compile successfully. Here is the debug log when trying to log in (twice). 

[debug export.log](https://github.com/Fabbi/autoshift/files/3793986/debug.export.log)

**Comment by DavidSpek** [comment]
So I installed Win64OpenSSL and Win32OpenSSL from https://slproweb.com/products/Win32OpenSSL.html. After doing this I was able to successfully log in. Seems like this would be something more people will run into.

**Comment by Fabbi** [comment]
Thanks for pointing this out. I didn't think of that dependency..

So everything is working now?

**Comment by DavidSpek** [comment]
Everything is now working, except the other bug I reported about the columns being shifted bord borderlands, BL2 and BL-TPS.

**Comment by DavidSpek** [comment]
First of all, the new changes have fixed the issues I had and the new source is also working great. I did need to remove the old database to get rid of the old incorrect entries that it was previously hanging on. Something new related to this issue popped up. I was wanting to use this for my girlfriend as well, so given the current setup, I made a new user account on the computer. In doing this I noticed a few strange things. They do not directly stop the program from functioning but I thought it would be good to report them. 

1.  After this was done I tried to simply copy the software folder I had compiled to her account, however, references were still being made to files located in my account. 

2. I recompiled the software on her user account and could not log in (her account on gearbox software needed to be activated which I had already been done). To check what was happening I started the software in verbose mode and then it proceeded to login to my account. How this was possible I am not sure. 

Initially, I thought I could not log in because of the OpenSSL, but that was not the case. Another thing I noticed, is that when switching between versions of the game, the software needs to be stopped and restarted instead of it dynamically switching. Not really an issue but I thought I should mention it.

**Comment by Fabbi** [comment]
Great to hear that everything so far was fixed.

Addressing your new reports:
1. Which files are still referenced? Did you copy the `*.dll` files, too?
2. Did you also copy the `AppData/Local/AutoShift` folder? There's the `.cookie.sav` file that you'd have to delete.
3. The need of "stopping and restarting" is a design-flaw in my code, I'll address that sometime maybe
4. Having checkboxes or some kind of means to activate multiple platforms/games is a good idea! 
5. The `please launch a SHiFT-enabled title`-thing is a limitation from gearbox I can't work around. It will automatically continue to redeem after 1hour

**Comment by DavidSpek** [comment]
I'm very sorry for the very late response. 
1. I did copy the Qt `*.dll` files along inside the folder. Sadly I can't seem to find which files were being referenced. However, if I remember correctly it was some of the Qt `*.dll's`. At the moment I don't have another Microsoft account I can use to test it with on the same system and on a VM this would be different anyway. 
2. I did not copy the `AppData/Local/AutoShift` folder as this would cause issues with which codes have been redeemed and having me already be logged in. 

What I have also noticed, Orcz for Borderlands 3 seems to only be listed under STEAM and not under EPIC. While this is incorrect as it is not yet available on steam, it does make the switching between the games easier. 

Also, I noticed an error stating the code was already redeemed but it looped and kept trying and wouldn't cross off the code as it does with the codes that are expired. After starting in verbose the code was marked off and the error didn't show anymore. I believe it was the code `CHKJ3-B6HHB-ZWBK5-3JJJT-CRHFJ` under BL3 on steam. What I did notice which seemed a bit strange after starting in verbose was the text `redeeming 255 Keys` right after `login successfull!` (successful has 1 l so that is a typo), even though all codes have already been redeemed or crossed off and it wasn't trying to redeem anything. 

Thank you for all the time and effort you are putting into this.

**Comment by Fabbi** [comment]
that it logged into your account is very very strange then.. does this still happen?

Maybe the code issue is the same error as in #23 .. Gearbox does some inconsistent stuff there..

`redeeming 255 keys` comes from the limit switch. It tells you that it will stop after that amount of keys. 


Thanks for pointing out the typo. English isn't my first language so I expect there to be many more of them :D

**Comment by DavidSpek** [comment]
The login hasn’t happened since, as I built a version on the user account I setup for her and then was able to login successfully. After being able to login, the cookie was of course saved so this hasn’t happened since. I might be able to test it on a different computer to see if I can replicate the issue.

**Comment by Fabbi** [comment]
stale
