### ISSUE TITLE
"TypeError: can only concatenate str (not "bytes") to str" when entering password

### ISSUE THREAD

**Issue by stevoisiak** [Fabbi/autoshift#2]
### Description

When I enter a password for initial login, autoshift crashes with `TypeError: can only concatenate str (not "bytes") to str`.

This occurs as soon as the first letter of the password is entered.

### Environment

- Windows 10 Home (Version 1803)
- Python 3.7.3 (32-bit)
- Run via Windows CMD

### Steps to recreate

1. Open CMD
2. Run `auto.py`
3. Type username and press Enter
4. Begin typing password

### Traceback

```
C:\Users\stevo\Downloads\autoshift-master>auto.py
First time usage: You need to login...
Username: test
Password: Traceback (most recent call last):
  File "C:\Users\stevo\Downloads\autoshift-master\auto.py", line 32, in <module>
    client = ShiftClient()
  File "C:\Users\stevo\Downloads\autoshift-master\shift.py", line 103, in __init__
    pw = input_pw("Password: ")
  File "C:\Users\stevo\Downloads\autoshift-master\shift.py", line 87, in input_pw
    pw += c
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by stevoisiak** [comment]
The error occurs on line 92 of Shift.py.

https://github.com/Fabbi/autoshift/blob/ffd4beb176df95fc6887e3b9ea21ef58259c7ff1/shift.py#L91-L92

A workaround would be decoding the bytes with `pw += c.decode()`. Although, there are other issues with Windows input, such as backspace not erasing the asterisks.

**Comment by Fabbi** [comment]
aw man, why didn't github tell me about your pull requests and this issue... sorry.

seems like windows has different keycodes for the backspace. I fixed it.
