### ISSUE TITLE
CPP Platform Incorrect

### ISSUE THREAD

**Issue by DavidSpek** [Fabbi/autoshift#20]
After trying to redeem codes for BL1, BL2 and BL-TPS I was seeing a lot of redemptions not go through. Upon looking at the codes and the list on ORCZ, I have found that the codes that show when steam is selected as platform are the codes from the PlayStation column on ORCZ. Likewise, when the platform PS is selected, codes from the XBOX column on ORCZ are shown (tested this for BL2). When the platform XBOX is selected the program crashes, probably because it is shifting columns when gathering the codes. As mentioned before, I think orcicorn might be a good addition or alternative as a source of codes.

**Comment by Fabbi** [comment]
I am in the middle of including orcicorn. I'll push the changes until Wednesday, promised
