### ISSUE TITLE
Where do I find my username/what format are cookies stored in?

### ISSUE THREAD

**Issue by flying-sausages** [Fabbi/autoshift#30]
First pre-condition, I'm running this on WSL2

Second: I created my account using an email. Except for the display name, I cannot find any other identifier. You cannot log into Shift website without an email though.

I tried everything, and i always have an empty `data/.cookies.save` file. If I knew what format was expected I could at least yank these values out my browser.

**Comment by Fabbi** [comment]
You need to quote your e-mail-address on command line! That should fix things. Manually creating the file is not that easy
