### ISSUE TITLE
A unknown Error occured when key already redeemed

### ISSUE THREAD

**Issue by Xebozone** [Fabbi/autoshift#32]
This only happens sometimes... It's not detecting the case where a key has already been redeemed:

Example:

[INFO]     Trying to redeem 5 Golden Keys (K3CJT-6BR3C-WJFJ9-JJTT3-JHSKZ)
[INFO]     Already redeemed 5 Golden Keys
..........
**[INFO]     Trying to redeem 1 Golden Key (W5WBB-9HRWF-F5RJR-WXJJB-BH9XZ)
[ERROR]    This SHiFT code has already been redeemed
[INFO]     A unknown Error occured**

**Comment by Fabbi** [comment]
this seems to be related to #23 . I have no clue, why some keys are doing this. (also there's a typo.. whoops 😃)
Are you using the Python or GUI Version?

**Comment by Xebozone** [comment]
Hey there.
Using the Python version on WSL.
Didn't know there was a GUI!

**Comment by Fabbi** [comment]
fixed in #27
