### ISSUE TITLE
Tiny Tina's Wonderland Codes Are Not Redeemed for Non-PC Platforms

### ISSUE THREAD

**Issue by therobd** [Fabbi/autoshift#39]
If you run the script for Tiny Tina's Wonderlands for any non-PC platform, then it will fail to find any codes. For example, here's the output for a fresh run where code "3TX3T-5T6CH-KKB5W-T3BTB-JCR53" should be valid with both ps and pc:

```console
./python3 auto.py -u username -p password --games ttw --platforms ps
Parsing TTW  keys...done. (no new Keys)
You have 0 golden TTW keys to redeem for PS
```

```console
./python3 auto.py -u username -p password --games ttw --platforms steam
Parsing TTW  keys...done. (no new Keys)
You have 0 golden TTW keys to redeem for STEAM
2022-05-07 22:22:43,888 [INFO]     Trying to redeem Skeleton Key (3TX3T-5T6CH-KKB5W-T3BTB-JCR53)
2022-05-07 22:22:44,585 [INFO]     The code `3TX3T-5T6CH-KKB5W-T3BTB-JCR53` is invalid
```

The reason that the code isn't being detected for PS is because the scraping code in query.py assumes that the Orcz page is in the same form as the [other Borderlands pages](http://orcz.com/Borderlands_2:_Golden_Key), namely that each ShiFT code is split by platform. Instead, all codes are universal and [are only listed once](http://orcz.com/Tiny_Tina%27s_Wonderlands:_Shift_Codes). Therefore, TTW codes must be parsed differently.

I'm unsure why Steam codes aren't being redeemed after being detected. That appears to be a separate issue.

**Comment by zarmstrong** [comment]
Steam codes might not be working cause the game isn't out for Steam yet?

**Comment by Fabbi** [comment]
I switched to the orcicorn source, so this should be fixed now.
I also implemented a way to handle multi-game keys.
