### ISSUE TITLE
Errors with v1.0

### ISSUE THREAD

**Issue by Torsdan** [Fabbi/autoshift#41]
On Win10 I get the following:
![image](https://user-images.githubusercontent.com/1498749/176063768-b781c560-ee9c-406d-9753-f2c4da35993e.png)
Using: .\auto.py --game bl3 ttw --platform epic --schedule -v --user "x" --pass "x"

And in Docker on Unraid I get:
> standard_init_linux.go:219: exec user process caused: exec format error

Using (in either Portainer or manual):
version: "3.0"
services:
  autoshift:
    image: fabianschweinfurth/autoshift:latest
    container_name: autoshift_all
    restart: always
    volumes:
      - /mnt/user/appdata/autoshift:/autoshift/data
    environment:
      - TZ=Australia/Brisbane
      - SHIFT_PLATFORMS=epic
      - SHIFT_USER=x
      - SHIFT_PASS=x
      - SHIFT_GAMES=bl3 ttw
      - SHIFT_ARGS=--schedule -v

**Comment by Fabbi** [comment]
which python version do you have?

**Comment by Fabbi** [comment]
I pushed a new docker image, could you try that one? It seems like building it on my arm64 mac makes it incompatible with x86.

**Comment by Fabbi** [comment]
there seems to be something wrong with your sources.. maybe call it with `python3 auto.py <...>` ?

**Comment by Torsdan** [comment]
Removed all other python installs. Doesn't recognise "python3 auto.py ..." but does try to run with "py auto.py ..." but:
![image](https://user-images.githubusercontent.com/1498749/176326619-db48129f-4179-4c5e-a81a-b1567e631b9a.png)

**Comment by Torsdan** [comment]
Nevermind that one, I forgot to upgrade the requirements, now it attempts to login, however:
![image](https://user-images.githubusercontent.com/1498749/176327630-e718d23d-2450-40b0-8896-38211f03825b.png)

**Comment by Fabbi** [comment]
that one got fixed in #35 😃 updating the source should do the trick

**Comment by Torsdan** [comment]
Thank you! It works now after grabbing the source zip, not the release zip. 😃
