### ISSUE TITLE
Feature request: more scheduling options

### ISSUE THREAD

**Issue by flammable** [Fabbi/autoshift#46]
I'm running four instances of AutoSHiFt as separate Docker containers, for myself and some friends. I've included `SHIFT_ARGS=--schedule -v` in my env file to run it once an hour, but I think I'm still hitting orcicorn's too frequently. Unfortunately, I've accidentally cleared the logs while troubleshooting #45, but I initially noticed some errors about accessing the site too much.

Would it be possible to have `--schedule` add a random start to each time the script checks for new keys? Or provide the option to run the script at specific times, so I can stagger them myself? I'd be fine with once a day, really.

If I remove `--schedule` from my env file, the script runs repeatedly. If the container did a check and stopped completely, I might be able to schedule this with cron on my Linux host.

Thanks again for this! I really appreciate your sharing AutoSHiFt. 😄

**Comment by Fabbi** [comment]
just released v1.1.0. you can now add `--schedule N` to run every N hours

**Comment by flammable** [comment]
Thank you!!
