### ISSUE TITLE
shift.cpp:70 Unknown error

### ISSUE THREAD

**Issue by zulfikar2** [Fabbi/autoshift#9]
![image](https://user-images.githubusercontent.com/10468869/59472659-3798f180-8e0d-11e9-8bd2-857da632488f.png)

It reedems a few and then errors out and won't stop. Have to alt+f4

**Comment by zulfikar2** [comment]
Restarting after deleting cache and keys.db file fixed it for a bit. It happened again. I fixed it for myself by clicking running and then clicking redeem x1 on a few items until it fixed itself. I assume it redeems it and doesn't tag it redeemed? And i manage to click the one that isnt actually redeemed which breaks the loop??

**Comment by Fabbi** [comment]
I think, I fixed it. You can find the new version under "Releases"
